[Platform.sh]: ElasticSearch support
ezsystems/ezplatform-ee pull request #148
Opened 2020-06-21 10:13 UTC by adamwojs

> JIRA: - 

### Description 

Added configuration template for ElasticSearch. 

_Note for reviewers: please review PR carefully. I'm pretty new to platform.sh ;-)_

### TODO

*   [ ] Confirm that ES 7.7 is available

2020-10-12 10:57 UTC, micszo requested changes
ES 7.7 is the latest available version: https://docs.platform.sh/configuration/services/elasticsearch.html#supported-versions.

2020-10-12 10:57 UTC, micszo commented on .platform.app.yaml
> +        ##php bin/console ezplatform:elasticsearch:put-index-template
There's an issue here. This gets executed on platform.sh after `composer ezplatform-install` which is followed by `ezplatform:reindex`.
Possibly this command should be moved before `HTTPCACHE_PURGE_TYPE="local" php -d memory_limit=-1 'which composer' ezplatform-install` on line 148. (that worked for QA) \cc @mnocon

2020-10-14 12:09 UTC, adamwojs commented
PR updated according to @micszo code review suggestions and rebased against 3.1 branch.

2020-10-14 12:39 UTC, micszo approved these changes
This order works. 👍

2020-10-14 12:41 UTC, merged

2020-10-14 12:41 UTC, lserwatka commented
@adamwojs could you merge it up and sideways?